### ISSUE TITLE
Configure Home Assistant MQTT Broker user-id and password

### ISSUE THREAD

**Issue by rkkhanna** [alexarch21/BLE-detect#3]
Hi Alex, I am hoping you can help with a question on configuring this on RPI Zero W 2.
I have my MQTT broker running on my HA (separate system). I have set up a user-id and password for the broker there.
How do I configure BLE-detect and provide the user-id and password in addition to the broker IP address?

Thanks for your help,

**Comment by alexarch21** [comment]
You'll have to modify the source code for that (but it's not hard). I'm using BLEdetect in a totally isolated subnet myself and I don't have a password on the MQTT broker. So I never added that option.

Just insert this after [line 320](https://github.com/alexarch21/BLE-detect/blob/b246f89adcbac6f8e7325c9b133f1f4e006518cd/src/beacon_detect.cpp#L320C49-L320C49) in the source:
```
conn_opts.username = "your mqtt username";
conn_opts.password = "your mqtt password";
```

I should probably add a config option for this.

**Comment by rkkhanna** [comment]
> conn_opts.password = "your mqtt password";

Much appreciated, Alex. Thank you for the quick response. Will try this out.
If I may, one other question regarding the sample text 'FFE0-FFE1' after colon (':') in known_devices.txt. Do these represent 'Major' and 'Minor' values for the beacon?

Thank you

**Comment by rkkhanna** [comment]
> You'll have to modify the source code for that (but it's not hard). I'm using BLEdetect in a totally isolated subnet myself and I don't have a password on the MQTT broker. So I never added that option.
> 
> Just insert this after [line 320](https://github.com/alexarch21/BLE-detect/blob/b246f89adcbac6f8e7325c9b133f1f4e006518cd/src/beacon_detect.cpp#L320C49-L320C49) in the source:
> 
> ```
> conn_opts.username = "your mqtt username";
> conn_opts.password = "your mqtt password";
> ```
> 
> I should probably add a config option for this.

Thanks, Alex. Much appreciated for the quick response.
I inserted the two lines starting at line 321 replacing username and password with my info. When I start 'bdetect' I get the following error message:

> [MQTT] Connecting with broker at http://192.168.xx.yy:1883...
> [MQTT] Failed to connect, return code -1

Any suggestions what could be the issue? Though the password has special characters I have enclosed it in quotes ("). Quote character itself is not in the password value.

BTW, I needed to install openssl before I could successfully make paho MQTT client libraries.

Thank you for your help.

**Comment by alexarch21** [comment]
> Any suggestions what could be the issue?

You specified a http URL. MQTT is not http. Look at the example in the original source:

**tcp**://192.168.x.y:1883

> BTW, I needed to install openssl before I could successfully make paho MQTT client libraries.

If you build paho with SSL support enabled, then yes you will need openssl.

**Comment by rkkhanna** [comment]
> You specified a http URL. MQTT is not http. Look at the example in the original source:

🤦🏼‍♂️ Thank you for pointing this stupid mistake on my part. I am mortified.

Fixed it and got it to work! Now to play around with TX a bit to finetune detection distance.

Thank you so much for making this available and helping me get it up and running. 
Have a good weekend!

**Comment by alexarch21** [comment]
You're welcome. Glad that this helps someone other than myself ;)

Closing this issue then.
